### ISSUE TITLE
Question regarding retrain.py

### ISSUE THREAD

**Issue by alipov** [rpeden/cat-or-not#1]
Hi @rpeden, thank you for this awesome tutorial.
I have one question though: retrain.py defines **load_training_data()** function, but it's never get called. What is its purpose?

**Comment by rpeden** [comment]
@alipov Good catch! It is leftover code from an earlier version of the file. I deleted it on my dev machine, but it looks like I forgot to commit it to the repository. I've updated the file to remove the function. Thanks for asking about it!
